lib/puppet/util/network_device/transport_ftos/ssh.rb

SSL key is getting updated after resetting the switch and applying the new firmware image. Updated the SSH connection initiator to ignore the SSL key while creating a connection

ASM-2909 - Discovering dell_ftos fails when ssh host key is wrong

---

lib/puppet/type/force10_config.rb

Validation is added to have only alphanumeric characters in the name. It is just used as variable and no significance
The name created for ASM-Deployer is having certificate name which has an "-" in the name.

Removed validation of apply config namevar

---

lib/puppet/util/network_device/dell_ftos/possible_facts/hardware/m_series.rb

capturing the running configuration as facts. This is required for upload configuration feature where multiple configuration elements needs to be replaced

Capturing running configuration of the switch as facts

---

lib/puppet/provider/force10_config/dell_ftos.rb
lib/puppet/provider/force10_firmwareupdate/dell_ftos.rb

Updated the reload-type to normal-reload to ensure that the switch is not in BMP mode after reload

ASM-3105 If IOA is configured in BMP mode ASM cannot configure it

---

lib/puppet/util/network_device/dell_ftos/possible_facts/hardware/m_series.rb

Updated the facts table to capture the ethernet mode information of the IOA. This will be used for changing the switch to non-ethernet mode for IOA in PMUX mode

ASM-3106 ASM uplink configuration fails if IOA ports are configured in FC mode

---

lib/puppet/provider/force10_firmwareupdate/dell_ftos.rb

Instead of saying "unsuccessful" return the output message for better
debugging

Better failure message on fw update

---

lib/puppet/provider/force10_firmwareupdate/dell_ftos.rb

show reload-type command is not supported on IOAs which is used for disabling BMP mode on the switches. Added a skip check for IO Aggregator and SNIOA.

ASM-3361 Firmware update fails on IOAs

---

lib/puppet/util/network_device/dell_ftos/possible_facts/base.rb

Discovery for S4820T switch is not capturing the facts which are required for ASM ToR configuration. Updated the regular expression to support all S48xx switches considering them same as S4810

ASM-3475 Rack server switch configuration failed

---

lib/puppet/util/network_device/dell_ftos/model/scoped_value.rb

Added the null check while defining the scope variable.

ASM-4010 S5000 Zoneset configuration is failing

---

bin/discovery.rb

This was breaking discovery on new appliances

Fixed default port in discovery script

---

bin/discovery.rb
lib/puppet_x/force10/transport.rb

An encrypted device password was passed to the asm-deployer device
management service and written to the device configuration file
url. That password has been deprecated and all puppet-layer code
should use the credential_id argument in preference to that.
Additionally the credential-id argument will no longer be passed to
inventory scripts since it is redundant -- the information contained
in it is already passed as separate plaintext arguments.

ASM-3406 remove asm_decrypt password encryption

---

lib/puppet/provider/dell_ftos.rb
lib/puppet/type/force10_zone.rb
lib/puppet/type/force10_zoneset.rb
lib/puppet_x/force10/model/zone/base.rb

During refactoring to use Puppet apply, I had changed the providers to extend Puppet::Provider, and leaving the types as ensurable caused issues.  Later on, the providers were changed to use Puppet::Provider::NetworkDevice, which predefine the methods that ensurable needed that caused it to fail on Puppet::Provider.  ensurable provides some methods that zone/zoneset rely on to be setup correctly.
In particular, one of the methods that is invoked for ensure => :present is the one that correctly sets the properties that we want to set and without that, the properties were not updating correctly.
I'm not sure why this doesn't seem to cause issues with other providers which seem to be working fine, but this is something to keep in mind if we see similar issues.

Zone and zoneset need to be ensurable to work correctly

---

lib/puppet_x/force10/transport/ssh.rb

The upgrade system command takes a very long time to complete.
Also, Intermittent errors when sending command with \n.  Use \r instead

Firmware update timeouts

---

lib/puppet_x/force10/possible_facts/hardware/m_series.rb
lib/puppet_x/force10/possible_facts/hardware/s_series.rb

Change this fact to be a list of hashes.
From:
` { “interface name” => { :interface, :location, :remote_mac } } `
To:
`[ {:interface, :location, :remote_mac } ]`
example output:  https://gist.github.com/logankimmel/e6f2e553a2be2e4b096e

ASM-5116 remote_device_info fact as list

---

lib/puppet/provider/force10_firmwareupdate/dell_ftos.rb

Remove binary files from the flash directory on switches.
We've seen firmware updates fail when there is no space left to
flas the new binary

ASM-2546  Remove binaries files from flash dir

---

lib/puppet_x/force10/possible_facts/base.rb
lib/puppet_x/force10/possible_facts/hardware/ioa.rb
lib/puppet_x/force10/possible_facts/hardware/s_series.rb
spec/fixtures/show_running_config_interface
spec/spec_helper.rb
spec/unit/puppet_x/force10/possible_facts/hardware/ioa_spec.rb

IOA vlan_information requires different parsing method as
the interface info isn't in the vlan info block in `show running-config interfaces`
output.  test included

ASM-5383 Vlan_information fact for IOA

---

lib/puppet_x/force10/possible_facts/base.rb
lib/puppet_x/force10/possible_facts/hardware/ioa.rb
spec/unit/puppet_x/force10/possible_facts/hardware/ioa_spec.rb

The values need to be strings and not arrays in order to be consistant
with the other modules

ASM-5383-2 Vlan-information values as strings

---

lib/puppet/provider/force10_interface/dell_ftos.rb
spec/unit/puppet/provider/force10_interface/dell_ftos_spec.rb

Recent changes overrode the parent provider's exists? method, which resulted in properties sometimes not being applied. The parent provider can be found here:
https://github.com/puppetlabs/puppet/blob/c2d2d7dda48cd948bf21df250bc45b431c571235/lib/puppet/provider/network_device.rb#L29

ASM-5309 ensure force10_interface properties applied

---

lib/puppet_x/force10/model/scoped_value.rb
spec/unit/puppet_x/force10/model/scoped_value_spec.rb

When a list is supplied as the value for the "untagged_vlan" param
in the `mxl_vlan` resource, we need to loop through these when checking
for other untagged vlans for this resource

ASM-5687 Checking for untagged VLAN's fails with list

---

lib/puppet_x/force10/possible_facts/hardware/s_series.rb

When an interface belongs to a port channel the module would create
facts with interface names like:
"TenGigabitEthernet 0/16 (Port-channel 11)"
this is a parsing error which this commit fixes

ASM-5569: Correctly detect interface names that belong to a PC

---

lib/puppet_x/force10/model/quadmode.rb

Added confirmation "yes" after enabling quad port command on the switch. this was missing in the existing flow

Quad Port command confirmation required with FTOS 9.8

---

lib/puppet_x/force10/model/quadmode.rb

For enabling / disabling quad mode on the interface, a confirmation prompt needs to be handled. Earlier PR was missing the intermediate prompt value.

ASM-5909 quadport mode not working for MXL

---

lib/puppet_x/force10/model/interface/base.rb
spec/unit/puppet_x/force10/model/interface/base_spec.rb

update_vlans wasn't removing VLANs from the opposing type causing
failures. For example, if you want to set VLAN 18 as untagged you need
to remove it as a tagged vlan if it exists there.

ASM-6017 remove VLANs from opposing type if needed

---

lib/puppet_x/force10/possible_facts/base.rb

FN IOAs which have a system types like "PE-FN-2210S-IOM" were not
recognized as M-series or S-series switches. Therefore some inventory
data like "show lldp neighbors" was not gathered. Add a system_type to
match them to the M-series switches, which hopefully they are pretty
similar to.

ASM-6055 Gather LLDP data for FN IOAs

---

lib/puppet_x/force10/model/interface/base.rb
spec/unit/puppet_x/force10/model/interface/base_spec.rb

Previously if an empty string was passed as tagged_vlan or
untagged_vlan for force10_interface the module would try to tag or
untag "" as the vlan rather than treating it as "no vlan". It still
had the intended behavior of removing other vlans and wouldn't fail
because this module currently pretty much eats all errors. That will
have to be fixed later...

ASM-5133 treat empty vlan string as empty list

---

lib/puppet_x/force10/possible_facts/hardware/m_series.rb

FNIOA model information is updated with FTOS 9.9. Included new patterns to be search for identification of FNIOA to enable uplink configuration

ASM-6127 Uplink configuration for IOAs is missing port information

---

lib/puppet_x/force10/model/scoped_value.rb
spec/unit/puppet_x/force10/model/scoped_value_spec.rb

This happens when a VLAN called something already exist, skip these
errors in all cases

ASM-6191: Do not fail on name errors

---

lib/puppet_x/force10/possible_facts/base.rb

included snmp commmunity string command that is to be used in nagios module for checking snmp string

ASM-6179 Dependency: added snmp_community string and stores as a fact.

---

lib/puppet_x/force10/possible_facts/hardware/m_series.rb
lib/puppet_x/force10/possible_facts/hardware/s_series.rb

When a remote system name is known it is shown in the lldp output and
chopped off if its too long:
Te 0/32      -                 78:45:c4:fc:0e:4b 78:45:c4:fc:0e:4b
Te 0/43      ESS-RowC-Rack7-...Eth1/18           54:7f:ee:b6:7c:79
the code assumed there will always be white space between fields
unfortunately here the ... is there instead.
This commit accepts either ... or whitespace there
Unfortunately the code also assumed the 'Rem Port Id' field is always a
mac, it clearly is not, this bug is still outstanding after this

ASM-6627: correct parsing of long hostnames

---

lib/puppet/type/force10_interface.rb
lib/puppet_x/force10/model/interface/base.rb
spec/fixtures/show_interfaces_switchport/show_switch_no_spt.out
spec/fixtures/show_interfaces_switchport/show_switch_spt.out
spec/unit/puppet_x/force10/model/interface/base_spec.rb
spec/unit/puppet_x/force10/model/interface_spec.rb

ASM will configure spanning-tree edge port to pvst alone. If user want to configure other edge port like MSTP, RSTP  then ASM will fail in configuring. 
Below changes will fix this issue.

ASM 6252, 6774 - updated to configure spanning-tree edge-port protocol

---

lib/puppet/provider/force10_settings/dell_ftos.rb
lib/puppet/type/force10_settings.rb
spec/unit/puppet/provider/force10_settings/dell_ftos_spec.rb

Code changes will configure Spanning-tree-protocol on switch based on user selection.

ASM-6253 Configring spanning-tree-protocol on switch

---

lib/puppet_x/force10/fact.rb
lib/puppet_x/force10/model/interface/base.rb
lib/puppet_x/force10/model/scoped_value.rb
lib/puppet_x/force10/possible_facts/hardware/m_series.rb
lib/puppet_x/force10/transport/ssh.rb
spec/fixtures/show_interfaces_switchport/show_switch_no_spt.out
spec/unit/puppet_x/force10/model/interface/base_spec.rb
spec/unit/puppet_x/force10/model/interface_spec.rb

code changes will some of Invalid commands in puppet model, while loading facts on switch.some invalid commands are 
1) Try to update default untagged vlan (1) which is invalid 
2) Error commands on stack-unit iom mode command while loading facts 
3)removed some commands which are like switch are already in config sate try to reenter it again will resolve these changes.

ASM-6083 dependency updated invalid commands on force10 puppet model

---

lib/puppet_x/force10/fact.rb
lib/puppet_x/force10/model/interface/base.rb
lib/puppet_x/force10/model/scoped_value.rb
lib/puppet_x/force10/possible_facts/hardware/m_series.rb
lib/puppet_x/force10/transport/ssh.rb
spec/fixtures/show_interfaces_switchport/show_switch_no_spt.out
spec/unit/puppet_x/force10/model/interface/base_spec.rb
spec/unit/puppet_x/force10/model/interface_spec.rb

Reverts dell-asm/dell-force10#108
This PR was causing failures on IOMs in P-MUX mode with:
Debug: SSH send: show system stack-port topology
Debug: ssh: expected show system stack-port topology
^
% Error: Invalid input at "^" marker.
IOMA1-test#
Error: Could not prefetch force10_portchannel provider 'dell_ftos': Invalid Command:     show system stack-port topology while configuring switch
/etc/puppetlabs/puppet/modules/force10/lib/puppet_x/force10/transport/ssh.rb:76:in `command'
/etc/puppetlabs/puppet/modules/force10/lib/puppet_x/force10/dsl.rb:74:in `block in evaluate_new_params'
/etc/puppetlabs/puppet/modules/force10/lib/puppet_x/force10/dsl.rb:69:in `each'
/etc/puppetlabs/puppet/modules/force10/lib/puppet_x/force10/dsl.rb:69:in `evaluate_new_params' …

Revert "ASM-6083 dependency updated invalid commands on force10 puppet model"

---

lib/puppet_x/force10/model/portchannel.rb
lib/puppet_x/force10/model/portchannel/generic.rb
lib/puppet_x/force10/model/scoped_value.rb

This led to issues of some config being removed/added every time we ran
puppet config, instead of skipping as you would expect. Particularly,
when configuring portmode, we remove existing config/vlans and that was
happening on every run, even if portmode was properly set

ASM-7342 Portchannel resources weren't properly matching existing config

---

lib/puppet_x/force10/model/interface/base.rb

For whatever reason, sometimes the port-channel-protocol command on
on a port will fail until 'no switchport' command is given. Since we
are already attempting to turn switchport mode off if it's enabled
anyway, we just ensure the command is run everytime, regardless of
whether it shows in the port's config.

ASM-7311 Always send a 'no switchport' command with portchannel

---

lib/puppet_x/force10/transport.rb

Force10 discovery and configuration command intermittently fails when there is ">" or ">>" character in the running configuration output.

ASM-7574 Force10 TOR switch configuration when there is ">" in output of running-configuration

---

lib/puppet_x/force10/model/interface/base.rb

switch defaulty behaves switchport mode even though there was no switchport on switch. passing no switchport before setting portmode will fix the Error existing in switch puppet sertname file.

ASM-7556 adding no switchport before setting portmode hybrid

---

lib/puppet_x/force10/transport.rb

Carriage return in the line ending was messing up our prompt for our SSH
expects, so some lines were hanging due to the carriage return being
seen as the beginning of the line that should have matched.

ASM-7652 Some IOAs would hang due to randomly returning DOS line endings

---

lib/puppet_x/force10/dsl.rb

The `:wrap` parameter is not valid for puppet 4.  I've tested this
to make sure the module still works on the old puppet wth discovery
and basic deployment.
Because a lot of this code was copy-pasted, I have a feeling this
was nevery needed (especially because it's set to false)

ASM-8827  Puppet4 compliance

---

Gemfile
lib/puppet/type/force10_interface.rb
lib/puppet/type/force10_portchannel.rb
lib/puppet_x/force10/model/interface/base.rb
lib/puppet_x/force10/model/portchannel/base.rb
spec/unit/puppet_x/force10/model/interface/base_spec.rb

Added support for new property "inclusive_vlans". When value if set to true then all existing vlans on the interface is retained and provided vlan is added to the list.

ASM-9659 Fix non-disruptive update to skip network configuration

---

lib/puppet_x/force10/model/portchannel/base.rb

For portchannel configuration inclusive_vlans parameter is not getting passed correctly. Include base configuration scopped configuration to ensure inclusive vlans value is available

ASM-9735 Switch Configuration failing deployments

---

Gemfile
lib/puppet/provider/force10_interface/dell_ftos.rb
lib/puppet/type/force10_interface.rb
lib/puppet/type/force10_vlan.rb
lib/puppet_x/force10/model/interface.rb
lib/puppet_x/force10/model/interface/base.rb
lib/puppet_x/force10/model/vlan/base.rb
lib/puppet_x/force10/possible_facts/base.rb

Still testing, since made changes to reduce code.
Added support for twenty five and hundred gig ports.  Fixed issue with all s-series switches, where command "show interface" will no longer accept shortened port names in 9.10.  Fixed issues with version checking where Dell is now Dell EMC, that breaks either in 9.11 or 9.12.
asm-core PR: https://github.com/dell-asm/asm-core/pull/3878
asm-deployer PR:  https://github.com/dell-asm/asm-deployer/pull/2438

VXFM-2167 Discover and service deployment s5048 support FTOS 9.11, 9.12 and S5048 switch

---

lib/puppet_x/force10/model/interface/base.rb

Previous commit was too aggressive in removing pre-existing
port-channels on an interface.

VXFM-2585 Do not remove port-channels we are trying to create

---

lib/puppet/type/force10_portchannel.rb
lib/puppet_x/force10/model/interface/base.rb
lib/puppet_x/force10/model/portchannel/generic.rb

Previously we vxfm used only portmode hybrid for force10. Portmode hybrid
should be removed for cases where there would online tagged vlans.

VXFM-5615 Removed using port-mode hybrid for no untagged vlan

---

lib/puppet_x/force10/possible_facts/hardware/m_series.rb
lib/puppet_x/force10/possible_facts/hardware/s_series.rb

In some cases the "Rem Host Name" field value is longer than the
column width. In that case it gets ellipsized and there is no space
between it and the next column:
Loc PortID     Rem Host Name     Rem Port Id                        Rem Chassis Id
--------------------------------------------------------------------------------
Te 1/3         localhost.local...e4:1d:2d:bf:d7:e0                  e4:1d:2d:bf:d7:e0
This was breaking the existing parsing which was rather ad-hoc. This
change uses a helper method in dell-asm-util to parse the data safely.

VXFM-9193 Handle long names in LLDP neighbors data
